[package]
name = "attrs"
version = "0.1.0"
authors = ["Adoo <Adoo@outlook.com>"]

[dependencies]
types = {path = "../../types"}
syn = { version ="*", features = ["full"]}
quote = "*"

[lib]
proc-macro = true