language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
before_deploy:
  - cargo doc
  - cargo login $CARGO_TOKEN
deploy:
  provider: script
  script: scripts/deploy.sh

  skip_cleanup: true
  on:
    tags: true