language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
before_deploy:
  - cargo login $CARGO_TOKEN
deploy:
  provider: script
  script:
    - cd types
    - cargo package 
    - cargo publish
    - cd ../macros/attrs
    - cargo package 
    - cargo publish
    - cd ../../
    - cargo package 
    - cargo publish
  on:
    tags: true